steps:
  # Backend - Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/hotel-reservation-microservice/hotel-backend', './Backend']

  # Backend - Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/hotel-reservation-microservice/hotel-backend']

  # Backend - Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hotel-backend'
      - '--image'
      - 'gcr.io/hotel-reservation-microservice/hotel-backend'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'

  # Frontend - Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/hotel-reservation-microservice/hotel-frontend', './frontend']

  # Frontend - Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/hotel-reservation-microservice/hotel-frontend']

  # Frontend - Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hotel-frontend'
      - '--image'
      - 'gcr.io/hotel-reservation-microservice/hotel-frontend'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000' 

images:
  - 'gcr.io/hotel-reservation-microservice/hotel-backend'
  - 'gcr.io/hotel-reservation-microservice/hotel-frontend'
