sonar.projectKey=IT21222122_HotelReservation_CTSE1
sonar.organization=it21222122
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=*/.test.js,*/.spec.js
sonar.exclusions=node_modules/*,dist/*