name: Snyk Security Scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Snyk on specific folders only (e.g., frontend and backend)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test ./frontend ./Backend --all-projects --prune-repeated-subdependencies --quiet
